Implement durable cleanup using Pub/Sub trigger

diff --git a/cloudbuild-cleanup.yaml b/cloudbuild-cleanup.yaml
--- a/cloudbuild-cleanup.yaml
+++ b/cloudbuild-cleanup.yaml
@@ -4,7 +4,12 @@ steps:
     args:
       - '-c'
       - |
-        cd tf/$_ENVIRONMENT
+        if [ -z "$_E2E_ENVIRONMENT" ]; then
+          echo "Error: _E2E_ENVIRONMENT is not set."
+          exit 1
+        fi
+        echo "Determined environment: $_E2E_ENVIRONMENT"
+        cd tf/$_E2E_ENVIRONMENT
         terraform init -backend-config=bucket=$PROJECT_ID-e2e-tfstate
         terraform workspace select $_TEST_RUN_ID
         terraform destroy -auto-approve -var=project_id=$PROJECT_ID -var=image=dummy -var=runtime=dummy
